//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Print.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USER
    {
        public string USR_ID { get; set; }
        public string NAME { get; set; }
        public string BMBH { get; set; }
        public string USR_PWD { get; set; }
        public string KFBH { get; set; }
        public string ROLE { get; set; }
        public string LXBH { get; set; }
        public string PY { get; set; }
        public string DHFSQX { get; set; }
        public string XG_PXZK_QX { get; set; }
        public string WLCHQX { get; set; }
        public string XTZY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public string USR_GROUP { get; set; }
        public string CZLX { get; set; }
        public Nullable<System.DateTime> CZRQ { get; set; }
        public string HQBH { get; set; }
        public string BZ { get; set; }
        public string SFZH { get; set; }
        public string XB { get; set; }
        public Nullable<System.DateTime> CSRQ { get; set; }
        public string MZ { get; set; }
        public string JG { get; set; }
        public string WHCD { get; set; }
        public string TC { get; set; }
        public string ZZ { get; set; }
        public string ZD { get; set; }
        public string SJ { get; set; }
        public string ZP { get; set; }
        public string CB { get; set; }
    }
}
