//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Print.MainWebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MainWebService.MainWebServiceSoap")]
    public interface MainWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteReturnInt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ExecuteReturnInt(out string errMsg, string spaceAndForm, string funcName, string[] dicParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteReturnTb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ExecuteReturnTb(out string errMsg, string spaceAndForm, string funcName, string[] dicParams);
        
        // CODEGEN: 参数“param”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlArrayItemAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteTrans", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Print.MainWebService.ExecuteTransResponse ExecuteTrans(Print.MainWebService.ExecuteTransRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteDynamicSql", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ExecuteDynamicSql(out string errMsg, string spaceAndForm, string funcName, string[] dicParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteDataset", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ExecuteDataset(out string errMsg, string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchSql", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SearchSql(out string errMsg, string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteCheckBoxTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ExecuteCheckBoxTable(out string errMsg, string spaceAndForm, string funcName, string[] dicParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchTbSqlWhere", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SearchTbSqlWhere(out string errMsg, string spaceAndForm, string funcName, string sqlWhere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ExecuteUpdate(out string errMsg, string selectSql, System.Data.DataTable changedDt);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteTrans", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteTransRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string spaceAndForm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string funcName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] param;
        
        public ExecuteTransRequest() {
        }
        
        public ExecuteTransRequest(string spaceAndForm, string funcName, string[][] param) {
            this.spaceAndForm = spaceAndForm;
            this.funcName = funcName;
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteTransResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteTransResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ExecuteTransResult;
        
        public ExecuteTransResponse() {
        }
        
        public ExecuteTransResponse(string ExecuteTransResult) {
            this.ExecuteTransResult = ExecuteTransResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MainWebServiceSoapChannel : Print.MainWebService.MainWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MainWebServiceSoapClient : System.ServiceModel.ClientBase<Print.MainWebService.MainWebServiceSoap>, Print.MainWebService.MainWebServiceSoap {
        
        public MainWebServiceSoapClient() {
        }
        
        public MainWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MainWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ExecuteReturnInt(out string errMsg, string spaceAndForm, string funcName, string[] dicParams) {
            return base.Channel.ExecuteReturnInt(out errMsg, spaceAndForm, funcName, dicParams);
        }
        
        public System.Data.DataTable ExecuteReturnTb(out string errMsg, string spaceAndForm, string funcName, string[] dicParams) {
            return base.Channel.ExecuteReturnTb(out errMsg, spaceAndForm, funcName, dicParams);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Print.MainWebService.ExecuteTransResponse Print.MainWebService.MainWebServiceSoap.ExecuteTrans(Print.MainWebService.ExecuteTransRequest request) {
            return base.Channel.ExecuteTrans(request);
        }
        
        public string ExecuteTrans(string spaceAndForm, string funcName, string[][] param) {
            Print.MainWebService.ExecuteTransRequest inValue = new Print.MainWebService.ExecuteTransRequest();
            inValue.spaceAndForm = spaceAndForm;
            inValue.funcName = funcName;
            inValue.param = param;
            Print.MainWebService.ExecuteTransResponse retVal = ((Print.MainWebService.MainWebServiceSoap)(this)).ExecuteTrans(inValue);
            return retVal.ExecuteTransResult;
        }
        
        public System.Data.DataTable ExecuteDynamicSql(out string errMsg, string spaceAndForm, string funcName, string[] dicParams) {
            return base.Channel.ExecuteDynamicSql(out errMsg, spaceAndForm, funcName, dicParams);
        }
        
        public System.Data.DataTable ExecuteDataset(out string errMsg, string sql) {
            return base.Channel.ExecuteDataset(out errMsg, sql);
        }
        
        public System.Data.DataTable SearchSql(out string errMsg, string sql) {
            return base.Channel.SearchSql(out errMsg, sql);
        }
        
        public System.Data.DataTable ExecuteCheckBoxTable(out string errMsg, string spaceAndForm, string funcName, string[] dicParams) {
            return base.Channel.ExecuteCheckBoxTable(out errMsg, spaceAndForm, funcName, dicParams);
        }
        
        public System.Data.DataTable SearchTbSqlWhere(out string errMsg, string spaceAndForm, string funcName, string sqlWhere) {
            return base.Channel.SearchTbSqlWhere(out errMsg, spaceAndForm, funcName, sqlWhere);
        }
        
        public int ExecuteUpdate(out string errMsg, string selectSql, System.Data.DataTable changedDt) {
            return base.Channel.ExecuteUpdate(out errMsg, selectSql, changedDt);
        }
    }
}
